### ISSUE TITLE
Release stable version of validation library

### ISSUE THREAD

**Issue by MaxTru** [camunda/element-templates-json-schema#5]
> **This is an epic issue which may be broken down into multiple tasks, if needed**

__What should we do?__

The element template json schema validation shall be used in downstream libraries (namely `properties-panel` and `Cawemo`) to validate provide `json`'s. For example a template shall not be published in Cawemo, if it is not valid. 

In general, this library consists of two components
* a JSON Schema which can be used out of the box in other tools ([`resources/element-templates.schema.json`](https://github.com/bpmn-io/element-templates-json-schema/blob/master/resources/element-templates.schema.json))
* a validation module on top of `ajv` which provides API to validate single and multiple element templates (`lib`)

This results in different usage scenarios for our schema
* Cawemo might use the standalone schema inside its Monaco Editor, for a generic JSON Form
* Properties Panel might use the validation library (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/386)

Therefore this epic shall include:

- [x] Provide stable interface to perform json validation
  - [x] Provide stable JSON schema file
    - [x] Add new template `version` property: number property
    - [x] More combinations #9 
  - [x] Provide stable validation module
    - [x] Send more descriptive errors #3 
    - [x] Send all errors #8 
- [x] Support different schema versions
  - [x] Ensure backwards compatibility --> is achieved with `additionalProperties: true`
  - [x] Ensure release versions based on our [general release schema](https://github.com/bpmn-io/internal-docs/tree/master/release-schema)
  - [x] Separation of schema and validation library #11 
- [x] Provide basic usage example(s)
  - [x] Usage example for the standalone JSON Schema (cf. https://github.com/bpmn-io/element-templates-json-schema/issues/6#issuecomment-717831142)
  - [x] Usage example for the validation library
  - [x] Dedicated repository for those examples?
- [ ] Release stable version of this library 
  - [x] How to name the package?
    - schema: `@camunda/element-templates-json-schema`
    - validator: `@bpmn-io/json-schema-validator`
  - [x] Where to store the package?
    - https://www.npmjs.com/org/bpmn-io
    - https://www.npmjs.com/org/camunda-bpm
    - Somewhere else
  - [ ] optional: Store schema also in a central registry? #6 
     - This maybe won't be needed if we release the schema individually and just use tools like unpkg
  - [x] Do the initial release
    - [x] `@bpmn-io/json-schema-validator@0.1.0`
    - [x] `@camunda/element-templates-json-schema@0.1.0`

__Why should we do it?__

See above.

**Comment by pinussilvestrus** [comment]
This should also include https://github.com/bpmn-io/element-templates-json-schema/issues/3 to ensure better error messages.

**Comment by pinussilvestrus** [comment]
Also interesting: #6

**Comment by pinussilvestrus** [comment]
**Additional Question raised during the Kick off (29th October)**

It would make lots of sense if we split up the actual validation library and the schema in two different projects. 

* A split of concerns is needed because the schema and validation library can differ in its version
* Releasing both together, we would always use the version of the package, that would make it hard to determine the correct schema version of a JSON file

Benefits
* It would make it possible to specify the schema which will be used by the validation library 
* Element templates could simply specify the version of the schema (by providing the `$schema` property)
* The validation library would be then a @bpmn-io concern, the schema a @camunda concern
* It will be easier to create new element templates schemas (e.g. for Zeebe)
* It would make it possible to validate against different versions

Given the following example Template

```js
{
  "$schema": "https://bpmn.io/schema/element-templates/1.0.0",
  "name": "Foo",
  "id": "foo",
  "appliesTo": [
    "bpmn:Task"
  ],
  "properties": [
    {
      "label": "Are you awesome?",
      "type": "String",
      "value": true,
      "binding": {
        "type": "property",
        "name": "camunda:asyncBefore"
      }
    }
  ]
}
```

And the Properties Panel is using schema version 1.1.0

=> We can easily indicate a version mismatch and offer auto-migration etc.

**Comment by pinussilvestrus** [comment]
Excalidraw sketch to illustrate the new approach of separating the schema with the validation lib:

https://excalidraw.com/#json=4876578404171776,l_T6Dc-5IeSo5IR34z-M1A

**Comment by pinussilvestrus** [comment]
Released with https://github.com/camunda/element-templates-json-schema/commit/26189f783fd7c839651c6d5adc1a66e46d7efa29
